"""Add is_admin to User model

Revision ID: 83de25c1d0cc
Revises:
Create Date: 2025-06-30 17:40:10.565663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83de25c1d0cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Se você quiser que os usuários existentes não-admin tenham is_admin=False
    op.execute('UPDATE user SET is_admin = FALSE WHERE is_admin IS NULL')
    op.alter_column('user', 'is_admin', nullable=False, existing_type=sa.Boolean())
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###